language: java
jdk:
  - oraclejdk8
install: true
env:
 -TO_BUILD=FRONTEND
 -TO_BUILD=BACKEND
services:
  - docker
jobs:
  include:
      - stage: test
        script:
          - cd backend/nokia-innovative-project
          - chmod +x mvnw
          - mvn test
      - stage: build
        script:
        - if [ "$TO_BUILD" = FRONTEND ]; then cd frontend; npm i; fi
        - if [ "$TO_BUILD" = BACKEND ]; then cd backend/nokia-innovative-project; mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V; fi
      - stage: docker_build
        if: branch = master OR branch = develop AND type in (push)
        script:
          - docker build -t backend backend/nokia-innovative-project
          - docker tag backend innovativeprojectnokialibrary:backend $DOCKER_USERNAME/innovativeprojectnokialibrary
          - docker build -t frontend ../../frontend
          - docker tag frontend innovativeprojectnokialibrary:frontend $DOCKER_USERNAME/innovativeprojectnokialibrary
      - stage: docker_push
        if: branch = master OR branch = develop AND type in (push)
        script:
          - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          - docker push $DOCKER_USERNAME/innovativeprojectnokialibrary:frontend
          - docker push $DOCKER_USERNAME/innovativeprojectnokialibrary:backend
cache:
   directories:
    - $HOME/.m2
