language: java
jdk:
  - oraclejdk8
install: true
env:
 -HEROKU_API_KEY=$HEROKU_TOKEN
 -TAG=$TRAVIS_COMMIT_MESSAGE
services:
  - docker
before_install:
  - npm install -g @angular/cli
stages: 
  - name: test
  - name: build
  - name: docker_build
    if: branch = develop OR branch = develop
  - name: deploy
    if: branch = master
jobs:
  include:
      - stage: test
        script:
         - cd backend/nokia-innovative-project 
         - chmod +x mvnw 
         - mvn test
      - stage: build
        script:
         - cd frontend
         - npm i 
         - ng build --prod
         - ../backend/nokia-innovative-project mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - stage: docker_build
        script:
          - cd backend/nokia-innovative-project
          - mvn package
          - docker build -t $DOCKER_USERNAME/nokia.inno.lib.be:$TAG .
          - cd ../../frontend
          - npm install
          - npm install @types/node --save-dev
          - npm run build
          - docker build -t $DOCKER_USERNAME/nokia.inno.lib.fe:$TAG .
          - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          - docker push $DOCKER_USERNAME/nokia.inno.lib.be:$TAG
          - docker push $DOCKER_USERNAME/nokia.inno.lib.fe:$TAG
      - stage: deploy
        script: 
          - curl https://cli-assets.heroku.com/install-standalone.sh | sh
          - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
          - cd backend/nokia-innovative-project
          - mvn package -DskipTests
          - docker build -t registry.heroku.com/nokia-library-api/web -f Dockerfile.prod .
          - cd ../../frontend
          - npm install
          - npm install @types/node --save-dev
          - ng build --prod
          - docker build -t registry.heroku.com/nokia-library-client/web -f Dockerfile.prod .
          - docker push registry.heroku.com/nokia-library-api/web
          - docker push registry.heroku.com/nokia-library-client/web
          - /usr/local/bin/heroku container:release web -a nokia-library-api 
          - /usr/local/bin/heroku container:release web -a nokia-library-client 
cache:
   directories:
    - $HOME/.m2
