language: java
jdk:
  - oraclejdk8

env:
  - PROFILE
services:
  - docker

install:
  script:
    - cd frontend
    - npm i
    - cd ../../backend/nokia-innovative-project
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - cd backend/nokia-innovative-project
  - mvn test

jobs:
  include:
    - if: ((branch != master) OR (branch != develop)) AND (type IN (push)) 
      script:
    - if: (branch = master) AND (type IN (push))
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t backend .
        - docker tag backend innovativeprojectnokialibrary:backend $DOCKER_USERNAME/innovativeprojectnokialibrary
        - docker push $DOCKER_USERNAME/innovativeprojectnokialibrary
        - docker build -t frontend ../../frontend
        - docker tag frontend innovativeprojectnokialibrary:frontend $DOCKER_USERNAME/innovativeprojectnokialibrary
        - docker push $DOCKER_USERNAME/innovativeprojectnokialibrary
    - if: (branch = master) AND (type IN (push)) AND (tag IS present)
      script:
        # build with commit tag
    - if: (branch = develop) AND (type IN (push))
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t backend .
        - docker tag backend innovativeprojectnokialibrary:backend $DOCKER_USERNAME/innovativeprojectnokialibrary
        - docker push $DOCKER_USERNAME/innovativeprojectnokialibrary:backendtest
        - docker build -t frontend ../../frontend
        - docker tag frontend innovativeprojectnokialibrary:frontend $DOCKER_USERNAME/innovativeprojectnokialibrary
        - docker push $DOCKER_USERNAME/innovativeprojectnokialibrary:frontendtest
cache:
   directories:
    - $HOME/.m2
