
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080