spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc:
          lob:
            non_contextual_creation: true
      properties:
        higernate:
          temp:
            use_jdbc_metadata_defaults: false
    open-in-view: false

