spring:
  profiles:
    active: development
  mail:
    host: smtp.gmail.com
    username: nokia.library@gmail.com
    password: NokiaLibrary2018
    port: 587
    properties:
      mail:
        transport.protocl: smtp
        smtp:
          auth: true
          starttls.enable: true
    debug: true