INSERT INTO book_status (status_name) VALUES ('AVAILABLE');
INSERT INTO book_status (status_name) VALUES ('AWAITING');
INSERT INTO book_status (status_name) VALUES ('BORROWED');
INSERT INTO book_status (status_name) VALUES ('RESERVED');
INSERT INTO book_status (status_name) VALUES ('UNAVAILABLE');

INSERT INTO book_category (book_category_name) VALUES ('guide');
INSERT INTO book_category (book_category_name) VALUES ('programming');
INSERT INTO book_category (book_category_name) VALUES ('education');
INSERT INTO book_category (book_category_name) VALUES ('astronomy');
INSERT INTO book_category (book_category_name) VALUES ('science');
INSERT INTO book_category (book_category_name) VALUES ('java');
INSERT INTO book_category (book_category_name) VALUES ('c++');
INSERT INTO book_category (book_category_name) VALUES ('cpp');
INSERT INTO book_category (book_category_name) VALUES ('javascript');
INSERT INTO book_category (book_category_name) VALUES ('react');
INSERT INTO book_category (book_category_name) VALUES ('frontend');
INSERT INTO book_category (book_category_name) VALUES ('testing');
INSERT INTO book_category (book_category_name) VALUES ('design');
INSERT INTO book_category (book_category_name) VALUES ('lte');
INSERT INTO book_category (book_category_name) VALUES ('managment');

INSERT INTO address (building, city) VALUES ('West Link', 'Wrocław');
INSERT INTO address (building, city) VALUES ('Eest Link', 'Wrocław');
INSERT INTO address (building, city) VALUES ('Blue Tower', 'Wrocław');


INSERT INTO "user" (email, first_name, last_name, password, address_id)
VALUES ('user@user.com', 'User', 'User', '$2a$10$q42WZU7b.2emX8QlMwWV/.WWY.hSAB5by6mI1Tkq58XMi7ij0KbBy', 1);

INSERT INTO "user" (email, first_name, last_name, password, address_id)
VALUES ('wojtek@admin.com', 'Wojtek', 'Wojciechowski', '$2a$10$Ro6ctBdfMovhKqJdYFgnrO58tTf3uQ7hrY9tm93Uclb0fiP3fQMKS', 1);

INSERT INTO "user" (email, first_name, last_name, password, address_id)
VALUES ('jacek@admin.com', 'Jacek', 'Jackowski', '$2a$10$Ro6ctBdfMovhKqJdYFgnrO58tTf3uQ7hrY9tm93Uclb0fiP3fQMKS', 1);

INSERT INTO "user" (email, first_name, last_name, password, address_id)
VALUES ('alex@admin.com', 'Alex', 'Alexowski', '$2a$10$Ro6ctBdfMovhKqJdYFgnrO58tTf3uQ7hrY9tm93Uclb0fiP3fQMKS', 1);

INSERT INTO "user" (email, first_name, last_name, password, address_id)
VALUES ('mikolaj@admin.com', 'Mikołaj', 'Mikołajski', '$2a$10$Ro6ctBdfMovhKqJdYFgnrO58tTf3uQ7hrY9tm93Uclb0fiP3fQMKS', 1);

INSERT INTO "user" (email, first_name, last_name, password, address_id)
VALUES ('janusz.kowalski@user.com', 'Janusz', 'Kowalski', '$2a$10$q42WZU7b.2emX8QlMwWV/.WWY.hSAB5by6mI1Tkq58XMi7ij0KbBy', 1);

INSERT INTO "user" (email, first_name, last_name, password, address_id, is_account_active)
VALUES ('admin@admin.com', 'Admin', 'Adminowski', '$2a$10$Ro6ctBdfMovhKqJdYFgnrO58tTf3uQ7hrY9tm93Uclb0fiP3fQMKS', 1, true);

INSERT INTO "user" (email, first_name, last_name, password, address_id, is_account_active)
VALUES ('nokia.library@gmail.com', 'Nokia', 'Library', '$2a$10$Ro6ctBdfMovhKqJdYFgnrO58tTf3uQ7hrY9tm93Uclb0fiP3fQMKS', 1, true);



INSERT INTO role (role) VALUES ('ROLE_EMPLOYEE');
INSERT INTO role (role) VALUES ('ROLE_ADMIN');
INSERT INTO user_roles (user_id, roles_id) VALUES (1, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (2, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (2, 2);
INSERT INTO user_roles (user_id, roles_id) VALUES (3, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (3, 2);
INSERT INTO user_roles (user_id, roles_id) VALUES (4, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (4, 2);
INSERT INTO user_roles (user_id, roles_id) VALUES (5, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (5, 2);
INSERT INTO user_roles (user_id, roles_id) VALUES (6, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (7, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (7, 2);
INSERT INTO user_roles (user_id, roles_id) VALUES (8, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (8, 2);

INSERT INTO author (author_full_name) VALUES ('Amy Muntz');
INSERT INTO author (author_full_name) VALUES ('Etienne Wenger');
INSERT INTO author (author_full_name) VALUES ('Patrick Lencioni');
INSERT INTO author (author_full_name) VALUES ('Gary Hamel');
INSERT INTO author (author_full_name) VALUES ('Andrei Alexandrescu');
INSERT INTO author (author_full_name) VALUES ('Sreekrishnan Venkateswaran');
INSERT INTO author (author_full_name) VALUES ('Christopher Hallinan');
INSERT INTO author (author_full_name) VALUES ('Herb Sutter');
INSERT INTO author (author_full_name) VALUES ('Stephen D. Huston');
INSERT INTO author (author_full_name) VALUES ('Douglas C. Schmidt');
INSERT INTO author (author_full_name) VALUES ('Barbara E. Moo');
INSERT INTO author (author_full_name) VALUES ('Andrew Koenig');
INSERT INTO author (author_full_name) VALUES ('Jeffrey Pfeffer');
INSERT INTO author (author_full_name) VALUES ('Robert I. Sutton');
INSERT INTO author (author_full_name) VALUES ('red. prowadzący Tomasz Janoś');
INSERT INTO author (author_full_name) VALUES ('Robert C. Martin');
INSERT INTO author (author_full_name) VALUES ('Paul M. Duvall');
INSERT INTO author (author_full_name) VALUES ('Michael C. Feathers');
INSERT INTO author (author_full_name) VALUES ('Ken Schwaber');
INSERT INTO author (author_full_name) VALUES ('Mike Beedle');
INSERT INTO author (author_full_name) VALUES ('Gerard Meszaros');
INSERT INTO author (author_full_name) VALUES ('Diana Larsen');
INSERT INTO author (author_full_name) VALUES ('Esther Derby');
INSERT INTO author (author_full_name) VALUES ('Kent Beck');
INSERT INTO author (author_full_name) VALUES ('Jenifer Tidwell');
INSERT INTO author (author_full_name) VALUES ('Clemens Szyperski');
INSERT INTO author (author_full_name) VALUES ('William Opdyke');
INSERT INTO author (author_full_name) VALUES ('Martin Fowler');
INSERT INTO author (author_full_name) VALUES ('John Brant');
INSERT INTO author (author_full_name) VALUES ('Don Roberts');
INSERT INTO author (author_full_name) VALUES ('Doug Lea');
INSERT INTO author (author_full_name) VALUES ('Joshua Bloch');
INSERT INTO author (author_full_name) VALUES ('Jenifer TidwellBrian Goetz');
INSERT INTO author (author_full_name) VALUES ('Joseph Bowbeer');
INSERT INTO author (author_full_name) VALUES ('David Holmes');
INSERT INTO author (author_full_name) VALUES ('Tim Peierls');
INSERT INTO author (author_full_name) VALUES ('Bruce Eckel');
INSERT INTO author (author_full_name) VALUES ('Jerzy Grębosz');
INSERT INTO author (author_full_name) VALUES ('Stephen Prata');
INSERT INTO author (author_full_name) VALUES ('Jesper Pedersen et al.');
INSERT INTO author (author_full_name) VALUES ('Matthias Kalle Dalheimer');
INSERT INTO author (author_full_name) VALUES ('Stanley B.Lipman');
INSERT INTO author (author_full_name) VALUES ('Jeff Garlan Richard Anthony');
INSERT INTO author (author_full_name) VALUES ('opracowanie zbiorowe');
INSERT INTO author (author_full_name) VALUES ('Andrew J. Viterbi');
INSERT INTO author (author_full_name) VALUES ('Erik Dahlman');
INSERT INTO author (author_full_name) VALUES ('Per Beming');
INSERT INTO author (author_full_name) VALUES ('Stefan Parkvall');
INSERT INTO author (author_full_name) VALUES ('Johan Skold');
INSERT INTO author (author_full_name) VALUES ('Tektronix Berlin GmbH & Co');
INSERT INTO author (author_full_name) VALUES ('KG');
INSERT INTO author (author_full_name) VALUES ('Thierry Lucidarme');
INSERT INTO author (author_full_name) VALUES ('Pierre Lescuyer');
INSERT INTO author (author_full_name) VALUES ('Andrzej Niemczyk');
INSERT INTO author (author_full_name) VALUES ('Anna Niemczyk');
INSERT INTO author (author_full_name) VALUES ('Jan Mądry');
INSERT INTO author (author_full_name) VALUES ('Andrew Hunt');
INSERT INTO author (author_full_name) VALUES ('David Hunt');
INSERT INTO author (author_full_name) VALUES ('Manfred Nuber');
INSERT INTO author (author_full_name) VALUES ('Rainer Handel');
INSERT INTO author (author_full_name) VALUES ('Stefan Shroeder');
INSERT INTO author (author_full_name) VALUES ('Cynthia Anders');
INSERT INTO author (author_full_name) VALUES ('Randall Hyde');
INSERT INTO author (author_full_name) VALUES ('Donald E. Knuth');
INSERT INTO author (author_full_name) VALUES ('Rick Mugridge');
INSERT INTO author (author_full_name) VALUES ('Ward Cunningham');
INSERT INTO author (author_full_name) VALUES ('John L.Hennessy');
INSERT INTO author (author_full_name) VALUES ('David A. Patterson');
INSERT INTO author (author_full_name) VALUES ('Michael Barr & Anthony Massa');
INSERT INTO author (author_full_name) VALUES ('Stephen C. Dewhurst');
INSERT INTO author (author_full_name) VALUES ('Ron Patton');
INSERT INTO author (author_full_name) VALUES ('Joshua Kerievsky');
INSERT INTO author (author_full_name) VALUES ('N/A');
INSERT INTO author (author_full_name) VALUES ('Chris Crouch');
INSERT INTO author (author_full_name) VALUES ('Pat Nickerson');
INSERT INTO author (author_full_name) VALUES ('Alec Mackenzie');
INSERT INTO author (author_full_name) VALUES ('David E. Simon');
INSERT INTO author (author_full_name) VALUES ('James R. Trott');
INSERT INTO author (author_full_name) VALUES ('Alan Shalloway');
INSERT INTO author (author_full_name) VALUES ('Mary and Tom Poppendieck');
INSERT INTO author (author_full_name) VALUES ('Andreas Zeller');
INSERT INTO author (author_full_name) VALUES ('Steve Loughran');
INSERT INTO author (author_full_name) VALUES ('Erik Hatcher');
INSERT INTO author (author_full_name) VALUES ('Kevin A. Lee');
INSERT INTO author (author_full_name) VALUES ('Steve Holzner');
INSERT INTO author (author_full_name) VALUES ('Alistair Cockburn');
INSERT INTO author (author_full_name) VALUES ('Norman Matloff');
INSERT INTO author (author_full_name) VALUES ('Peter Jay Salzman');
INSERT INTO author (author_full_name) VALUES ('Henrik Kniberg');
INSERT INTO author (author_full_name) VALUES ('Paul Hamill');
INSERT INTO author (author_full_name) VALUES ('Richard D. Lewis');
INSERT INTO author (author_full_name) VALUES ('Terttu Leney');
INSERT INTO author (author_full_name) VALUES ('Bas Vodde');
INSERT INTO author (author_full_name) VALUES ('Craig Larman');
INSERT INTO author (author_full_name) VALUES ('Martin Sauter');
INSERT INTO author (author_full_name) VALUES ('John Lakos');
INSERT INTO author (author_full_name) VALUES ('Jeffrey K. Linker');
INSERT INTO author (author_full_name) VALUES ('Mike Cohn');
INSERT INTO author (author_full_name) VALUES ('Daniel Pravat');
INSERT INTO author (author_full_name) VALUES ('Mario Hewardt');
INSERT INTO author (author_full_name) VALUES ('Colin Willbock');
INSERT INTO author (author_full_name) VALUES ('Thomas Deiss');
INSERT INTO author (author_full_name) VALUES ('Stefan Keil');
INSERT INTO author (author_full_name) VALUES ('Stephan Tobies');
INSERT INTO author (author_full_name) VALUES ('Bert Bates');
INSERT INTO author (author_full_name) VALUES ('Kathy Sierra');
INSERT INTO author (author_full_name) VALUES ('Arnold Robbins');
INSERT INTO author (author_full_name) VALUES ('Richard McDougall');
INSERT INTO author (author_full_name) VALUES ('Jim Mauro');
INSERT INTO author (author_full_name) VALUES ('Michael D. Bauer');
INSERT INTO author (author_full_name) VALUES ('Paul DuBois');
INSERT INTO author (author_full_name) VALUES ('Dan Rubel');
INSERT INTO author (author_full_name) VALUES ('Eric Clayberg');
INSERT INTO author (author_full_name) VALUES ('Neal Gafter');
INSERT INTO author (author_full_name) VALUES ('Shelley Powers');
INSERT INTO author (author_full_name) VALUES ('Mike Loukides');
INSERT INTO author (author_full_name) VALUES ('Jerry Peek');
INSERT INTO author (author_full_name) VALUES ('Tim O''Reilly');
INSERT INTO author (author_full_name) VALUES ('Klaus Schmidt');
INSERT INTO author (author_full_name) VALUES ('Erich Gamma');
INSERT INTO author (author_full_name) VALUES ('Lee Nackman');
INSERT INTO author (author_full_name) VALUES ('John Wiegand');
INSERT INTO author (author_full_name) VALUES ('Raj Jain');
INSERT INTO author (author_full_name) VALUES ('Mahbub Hassan');
INSERT INTO author (author_full_name) VALUES ('Nathan Torkington');
INSERT INTO author (author_full_name) VALUES ('Tom Christiansen');
INSERT INTO author (author_full_name) VALUES ('Amr Elssamadisy');
INSERT INTO author (author_full_name) VALUES ('Liz Sedley');
INSERT INTO author (author_full_name) VALUES ('Rachel Davies');
INSERT INTO author (author_full_name) VALUES ('David West');
INSERT INTO author (author_full_name) VALUES ('Brett D. McLaughlin');
INSERT INTO author (author_full_name) VALUES ('Gary pollice');
INSERT INTO author (author_full_name) VALUES ('Bill Calkins');
INSERT INTO author (author_full_name) VALUES ('David Astels');
INSERT INTO author (author_full_name) VALUES ('Terry Camerlengo');
INSERT INTO author (author_full_name) VALUES ('Andrew Monkhouse');
INSERT INTO author (author_full_name) VALUES ('Charlie Russel');
INSERT INTO author (author_full_name) VALUES ('Jason Gerend');
INSERT INTO author (author_full_name) VALUES ('Sharon Crawford');
INSERT INTO author (author_full_name) VALUES ('Mauricio Arregoces');
INSERT INTO author (author_full_name) VALUES ('Marizio Portolani');
INSERT INTO author (author_full_name) VALUES ('Mike Wilson');
INSERT INTO author (author_full_name) VALUES ('Steva Northhover');
INSERT INTO author (author_full_name) VALUES ('Lasse Koskela');
INSERT INTO author (author_full_name) VALUES ('Benjamin C. Pierce');
INSERT INTO author (author_full_name) VALUES ('Eric Freeman');
INSERT INTO author (author_full_name) VALUES ('Elisabeth Freeman');
INSERT INTO author (author_full_name) VALUES ('Kimball Fisher');
INSERT INTO author (author_full_name) VALUES ('Steve McConnell');
INSERT INTO author (author_full_name) VALUES ('Miro Samek');
INSERT INTO author (author_full_name) VALUES ('J. Richard Hackman');
INSERT INTO author (author_full_name) VALUES ('Hans Van Vliet');
INSERT INTO author (author_full_name) VALUES ('Sean Convery');
INSERT INTO author (author_full_name) VALUES ('Phillip A. Laplante');
INSERT INTO author (author_full_name) VALUES ('Colin J. Neil');
INSERT INTO author (author_full_name) VALUES ('Nancy Walsh');
INSERT INTO author (author_full_name) VALUES ('Steve Lidie');
INSERT INTO author (author_full_name) VALUES ('Ralph Johnson');
INSERT INTO author (author_full_name) VALUES ('John Vlissides');
INSERT INTO author (author_full_name) VALUES ('Richard Helm');
INSERT INTO author (author_full_name) VALUES ('Scott Meyers');
INSERT INTO author (author_full_name) VALUES ('P.J. Plauger');
INSERT INTO author (author_full_name) VALUES ('Nicolai M. Josuttis');
INSERT INTO author (author_full_name) VALUES ('Harvey Deitel');
INSERT INTO author (author_full_name) VALUES ('Paul Deitel');
INSERT INTO author (author_full_name) VALUES ('Jonathan P. Castro');
INSERT INTO author (author_full_name) VALUES ('Anita Rosen');
INSERT INTO author (author_full_name) VALUES ('Larry Wall');
INSERT INTO author (author_full_name) VALUES ('Jon Orwant');
INSERT INTO author (author_full_name) VALUES ('Bennet P. Lientz');
INSERT INTO author (author_full_name) VALUES ('Lee Larssen');
INSERT INTO author (author_full_name) VALUES ('Barbara Moo');
INSERT INTO author (author_full_name) VALUES ('Andrew Koening');
INSERT INTO author (author_full_name) VALUES ('Ken Jones');
INSERT INTO author (author_full_name) VALUES ('Brant B. Welch');
INSERT INTO author (author_full_name) VALUES ('Joel Spolsky');
INSERT INTO author (author_full_name) VALUES ('B. Walke');
INSERT INTO author (author_full_name) VALUES ('M. P. Althoff');
INSERT INTO author (author_full_name) VALUES ('P. Seidenberg');
INSERT INTO author (author_full_name) VALUES ('Judy McKay');
INSERT INTO author (author_full_name) VALUES ('Graham Bath');
INSERT INTO author (author_full_name) VALUES ('David Vandevoorde');
INSERT INTO author (author_full_name) VALUES ('J. Cichocki');
INSERT INTO author (author_full_name) VALUES ('J. kołakowski');
INSERT INTO author (author_full_name) VALUES ('Robert Love');
INSERT INTO author (author_full_name) VALUES ('Alessandro Rubini');
INSERT INTO author (author_full_name) VALUES ('Greg Kroah-Hartman');
INSERT INTO author (author_full_name) VALUES ('Jonathan Corbet');
INSERT INTO author (author_full_name) VALUES ('T. Rudebusch');
INSERT INTO author (author_full_name) VALUES ('R. Kreher');
INSERT INTO author (author_full_name) VALUES ('Anne Mette');
INSERT INTO author (author_full_name) VALUES ('Jonassen Hass');
INSERT INTO author (author_full_name) VALUES ('Bruno Clerckx');
INSERT INTO author (author_full_name) VALUES ('Claude Oestges');
INSERT INTO author (author_full_name) VALUES ('Travis Russell');
INSERT INTO author (author_full_name) VALUES ('Microsoft course');
INSERT INTO author (author_full_name) VALUES ('Loutfi Nuaymi');
INSERT INTO author (author_full_name) VALUES ('Rajeev S. Koodli');
INSERT INTO author (author_full_name) VALUES ('Charles E. Perkins');
INSERT INTO author (author_full_name) VALUES ('Harri Holma');
INSERT INTO author (author_full_name) VALUES ('Antti Toskala');
INSERT INTO author (author_full_name) VALUES ('Rex Black');
INSERT INTO author (author_full_name) VALUES ('Jeffrey Bannister');
INSERT INTO author (author_full_name) VALUES ('Paul Mather');
INSERT INTO author (author_full_name) VALUES ('Sebastian Coope');
INSERT INTO author (author_full_name) VALUES ('David Thomas');
INSERT INTO author (author_full_name) VALUES ('Ian Paterson-Stephens');
INSERT INTO author (author_full_name) VALUES ('Andrew Bateman');
INSERT INTO author (author_full_name) VALUES ('Richard G. Lyons');
INSERT INTO author (author_full_name) VALUES ('W. Richard Stevens');
INSERT INTO author (author_full_name) VALUES ('James Noble');
INSERT INTO author (author_full_name) VALUES ('Charles Weir');
INSERT INTO author (author_full_name) VALUES ('Steve Kilts');
INSERT INTO author (author_full_name) VALUES ('Jeffrey D. Ullman');
INSERT INTO author (author_full_name) VALUES ('Monica S. Lam');
INSERT INTO author (author_full_name) VALUES ('Alfred V. Aho');
INSERT INTO author (author_full_name) VALUES ('Ravi Sethi');
INSERT INTO author (author_full_name) VALUES ('R. W. Hamming');
INSERT INTO author (author_full_name) VALUES ('Mathew Wilson');
INSERT INTO author (author_full_name) VALUES ('Gary Chefetz');
INSERT INTO author (author_full_name) VALUES ('Dale Howard');
INSERT INTO author (author_full_name) VALUES ('Sam Siewert');
INSERT INTO author (author_full_name) VALUES ('Douglas L. Perry');
INSERT INTO author (author_full_name) VALUES ('Rias Muhamed');
INSERT INTO author (author_full_name) VALUES ('Arunabha Ghosh');
INSERT INTO author (author_full_name) VALUES ('Jeffrey G. Andrews');
INSERT INTO author (author_full_name) VALUES ('Marc J. Rochkind');
INSERT INTO author (author_full_name) VALUES ('Brian Hook');
INSERT INTO author (author_full_name) VALUES ('David Abrahams');
INSERT INTO author (author_full_name) VALUES ('Aleksey Gurtovoy');
INSERT INTO author (author_full_name) VALUES ('Tom DeMarco');
INSERT INTO author (author_full_name) VALUES ('Timothy Lister');
INSERT INTO author (author_full_name) VALUES ('Mark Lutz');
INSERT INTO author (author_full_name) VALUES ('Stephen W. Smith');
INSERT INTO author (author_full_name) VALUES ('Stephen A. Rago');
INSERT INTO author (author_full_name) VALUES ('Hays W. ''Skip'' McCormick III');
INSERT INTO author (author_full_name) VALUES ('William J. Brown');
INSERT INTO author (author_full_name) VALUES ('Thomas J. Mowbray');
INSERT INTO author (author_full_name) VALUES ('Raphael C. Malveau');
INSERT INTO author (author_full_name) VALUES ('Gary R. Wright');
INSERT INTO author (author_full_name) VALUES ('Allan M. Stavely');
INSERT INTO author (author_full_name) VALUES ('Margaret A. Ellis');
INSERT INTO author (author_full_name) VALUES ('Bjarne Stroustrup');
INSERT INTO author (author_full_name) VALUES ('Volei A. Pedroni');
INSERT INTO author (author_full_name) VALUES ('Jacob West');
INSERT INTO author (author_full_name) VALUES ('Brian Chess');
INSERT INTO author (author_full_name) VALUES ('Christoph Rauscher');
INSERT INTO author (author_full_name) VALUES ('Bruce Powel Douglass');
INSERT INTO author (author_full_name) VALUES ('Robert V. Binder');
INSERT INTO author (author_full_name) VALUES ('Michael Barr');
INSERT INTO author (author_full_name) VALUES ('Jack Ganssle');
INSERT INTO author (author_full_name) VALUES ('Steve Vinoski');
INSERT INTO author (author_full_name) VALUES ('Michi Henning');
INSERT INTO author (author_full_name) VALUES ('William T. Vetterling');
INSERT INTO author (author_full_name) VALUES ('Brian P. Flannery');
INSERT INTO author (author_full_name) VALUES ('Saul A. Teukolsky');
INSERT INTO author (author_full_name) VALUES ('William H. Press');
INSERT INTO author (author_full_name) VALUES ('Flavio Muratore');
INSERT INTO author (author_full_name) VALUES ('Raymond Steele');
INSERT INTO author (author_full_name) VALUES ('Lajos Hanzo');
INSERT INTO author (author_full_name) VALUES ('Scott Hauck');
INSERT INTO author (author_full_name) VALUES ('Andre Dehon');
INSERT INTO author (author_full_name) VALUES ('Greg Gagne');
INSERT INTO author (author_full_name) VALUES ('Abraham Sielberschatz');
INSERT INTO author (author_full_name) VALUES ('Peter Baer Galvin');
INSERT INTO author (author_full_name) VALUES ('John Catsoulis');
INSERT INTO author (author_full_name) VALUES ('Frantisek Franek');
INSERT INTO author (author_full_name) VALUES ('Pete Becker');
INSERT INTO author (author_full_name) VALUES ('John R. Levine');
INSERT INTO author (author_full_name) VALUES ('Lloyd G. Williams');
INSERT INTO author (author_full_name) VALUES ('Connie U. Smith');
INSERT INTO author (author_full_name) VALUES ('Marco Cesati');
INSERT INTO author (author_full_name) VALUES ('Daniel P. Bovet');
INSERT INTO author (author_full_name) VALUES ('Amol Lad');
INSERT INTO author (author_full_name) VALUES ('Sriram Neelakandan');
INSERT INTO author (author_full_name) VALUES ('P. Raghavan');
INSERT INTO author (author_full_name) VALUES ('Niklaus Wirth');
INSERT INTO author (author_full_name) VALUES ('Stanley B. Lippman');
INSERT INTO author (author_full_name) VALUES ('Stephen R. Covey');
INSERT INTO author (author_full_name) VALUES ('Ken Blanchard');
INSERT INTO author (author_full_name) VALUES ('Spencer Johnson');
INSERT INTO author (author_full_name) VALUES ('Hal Burrows');
INSERT INTO author (author_full_name) VALUES ('William Oncken Jr.');
INSERT INTO author (author_full_name) VALUES ('IBM');
INSERT INTO author (author_full_name) VALUES ('Project Managment Institute');
INSERT INTO author (author_full_name) VALUES ('Stephen Withall');
INSERT INTO author (author_full_name) VALUES ('Jim Collins');
INSERT INTO author (author_full_name) VALUES ('Karl E. Wiegers');
INSERT INTO author (author_full_name) VALUES ('Alfie Kohn');
INSERT INTO author (author_full_name) VALUES ('Renee Baron');
INSERT INTO author (author_full_name) VALUES ('Bjorn Karlsson');
INSERT INTO author (author_full_name) VALUES ('Eric S. Roberts');
INSERT INTO author (author_full_name) VALUES ('Stephen Berczuk');
INSERT INTO author (author_full_name) VALUES ('Douglas Alger');
INSERT INTO author (author_full_name) VALUES ('Jan Ellsberger');
INSERT INTO author (author_full_name) VALUES ('Dieter Hogrefe');
INSERT INTO author (author_full_name) VALUES ('Steve Tockey');
INSERT INTO author (author_full_name) VALUES ('Alex Vrenios');
INSERT INTO author (author_full_name) VALUES ('Frederick P. Brooks Jr');
INSERT INTO author (author_full_name) VALUES ('Richard F. Raposa');
INSERT INTO author (author_full_name) VALUES ('Dafydd Stuttard and Marcus Pinto');
INSERT INTO author (author_full_name) VALUES ('Gladeana McMahon');
INSERT INTO author (author_full_name) VALUES ('Anne Archer');
INSERT INTO author (author_full_name) VALUES ('McAffer Jeff VanderLei Paul Archer Simon');
INSERT INTO author (author_full_name) VALUES ('McAffer Jeff Lemieux Jean-Michel Aniszczyk Chris');
INSERT INTO author (author_full_name) VALUES ('Rainsberger J.B.');
INSERT INTO author (author_full_name) VALUES ('Summerfield Mark');
INSERT INTO author (author_full_name) VALUES ('Abbott Doug');
INSERT INTO author (author_full_name) VALUES ('Donald G. Reinertsen');
INSERT INTO author (author_full_name) VALUES ('Peter M. Senge');
INSERT INTO author (author_full_name) VALUES ('Joseph G. Ecker');
INSERT INTO author (author_full_name) VALUES ('Anna Struzinska-Walczak          Krzysztof Walczak');
INSERT INTO author (author_full_name) VALUES ('Joe Celko');
INSERT INTO author (author_full_name) VALUES ('Jan L.Harrington');
INSERT INTO author (author_full_name) VALUES ('Zbigniew Rastabiga');
INSERT INTO author (author_full_name) VALUES ('Michal Florys');
INSERT INTO author (author_full_name) VALUES ('Corey Ladas');
INSERT INTO author (author_full_name) VALUES ('Martin Logan');
INSERT INTO author (author_full_name) VALUES ('Jez Humble');
INSERT INTO author (author_full_name) VALUES ('peter seibel');
INSERT INTO author (author_full_name) VALUES ('Michael Lopp');
INSERT INTO author (author_full_name) VALUES ('Gayle Laakmann');
INSERT INTO author (author_full_name) VALUES ('Elmasri Navathe');
INSERT INTO author (author_full_name) VALUES ('Steven S. Skiena');
INSERT INTO author (author_full_name) VALUES ('Stephen H. Kan');
INSERT INTO author (author_full_name) VALUES ('Joe Armstrong');
INSERT INTO author (author_full_name) VALUES ('David Mayhew');
INSERT INTO author (author_full_name) VALUES ('Dov Bulka');
INSERT INTO author (author_full_name) VALUES ('Johanna Rothman');
INSERT INTO author (author_full_name) VALUES ('Bruce Tate');
INSERT INTO author (author_full_name) VALUES ('Stanley Selkow');
INSERT INTO author (author_full_name) VALUES ('George Heineman');
INSERT INTO author (author_full_name) VALUES ('Andy Hunt');
INSERT INTO author (author_full_name) VALUES ('Dennis Shasha');
INSERT INTO author (author_full_name) VALUES ('William Wake');
INSERT INTO author (author_full_name) VALUES ('Jurgen Appelo');
INSERT INTO author (author_full_name) VALUES ('Eliyahu M. Goldratt');
INSERT INTO author (author_full_name) VALUES ('Jeff Cox');
INSERT INTO author (author_full_name) VALUES ('Chris Johnson');
INSERT INTO author (author_full_name) VALUES ('Farooq Khan');
INSERT INTO author (author_full_name) VALUES ('Moray Rumney');
INSERT INTO author (author_full_name) VALUES ('Neil Johnson');
INSERT INTO author (author_full_name) VALUES ('Jesse Lyn Stoner');
INSERT INTO author (author_full_name) VALUES ('Laurence Hawkins');
INSERT INTO author (author_full_name) VALUES ('Susan Fowler');
INSERT INTO author (author_full_name) VALUES ('Gerald M. Weinberg');
INSERT INTO author (author_full_name) VALUES ('Peter Hruschka');
INSERT INTO author (author_full_name) VALUES ('Suzanne Robertson');
INSERT INTO author (author_full_name) VALUES ('Steven McMenamin');
INSERT INTO author (author_full_name) VALUES ('James Robertson');
INSERT INTO author (author_full_name) VALUES ('Ben Casnocha');
INSERT INTO author (author_full_name) VALUES ('John C. Maxwell');
INSERT INTO author (author_full_name) VALUES ('Pamela Slim');
INSERT INTO author (author_full_name) VALUES ('Donald C. Gause');
INSERT INTO author (author_full_name) VALUES ('jessica livingston');
INSERT INTO author (author_full_name) VALUES ('Paul D. Tieger');
INSERT INTO author (author_full_name) VALUES ('Barbara Barron');
INSERT INTO author (author_full_name) VALUES ('Seppo Hamalainen');
INSERT INTO author (author_full_name) VALUES ('Henning Sanneck');
INSERT INTO author (author_full_name) VALUES ('Cinzia Sartori');
INSERT INTO author (author_full_name) VALUES ('Stephen J. Dubner');
INSERT INTO author (author_full_name) VALUES ('Steven D. Levitt');
INSERT INTO author (author_full_name) VALUES ('Elbert Hannah');
INSERT INTO author (author_full_name) VALUES ('Linda Lamb');
INSERT INTO author (author_full_name) VALUES ('Daniel H. Pink');
INSERT INTO author (author_full_name) VALUES ('Steven Levy');
INSERT INTO author (author_full_name) VALUES ('Jim Highsmith');
INSERT INTO author (author_full_name) VALUES ('Issam Toufik');
INSERT INTO author (author_full_name) VALUES ('Stefania Sesia');
INSERT INTO author (author_full_name) VALUES ('Matthew Baker');
INSERT INTO author (author_full_name) VALUES ('Dean Leffingwell');
INSERT INTO author (author_full_name) VALUES ('John Kotter');
INSERT INTO author (author_full_name) VALUES ('Christina Gessner');
INSERT INTO author (author_full_name) VALUES ('Michael Hiebel');
INSERT INTO author (author_full_name) VALUES ('Heinz Mellein');
INSERT INTO author (author_full_name) VALUES ('Reinhold Kruger');
INSERT INTO author (author_full_name) VALUES ('Venkat Subramaniam');
INSERT INTO author (author_full_name) VALUES ('Ka Wai Cheung');
INSERT INTO author (author_full_name) VALUES ('Craig Walls');
INSERT INTO author (author_full_name) VALUES ('Juergen Placht');
INSERT INTO author (author_full_name) VALUES ('Ralf Kreher');
INSERT INTO author (author_full_name) VALUES ('Torsten Ruedebusch');
INSERT INTO author (author_full_name) VALUES ('Juha Salmelin');
INSERT INTO author (author_full_name) VALUES ('Esa Metsala');
INSERT INTO author (author_full_name) VALUES ('Chad Fowler');
INSERT INTO author (author_full_name) VALUES ('Anshul Gupta');
INSERT INTO author (author_full_name) VALUES ('Vipin Kumar');
INSERT INTO author (author_full_name) VALUES ('Ananth Grama');
INSERT INTO author (author_full_name) VALUES ('George Karypis');
INSERT INTO author (author_full_name) VALUES ('Robert Lorber');
INSERT INTO author (author_full_name) VALUES ('Eunice Parisi-Carew');
INSERT INTO author (author_full_name) VALUES ('Donald Carew');
INSERT INTO author (author_full_name) VALUES ('Dick Ruhe');
INSERT INTO author (author_full_name) VALUES ('Paul J. Meyer');
INSERT INTO author (author_full_name) VALUES ('Don Shula');
INSERT INTO author (author_full_name) VALUES ('Daniel Kahneman');
INSERT INTO author (author_full_name) VALUES ('J. Stewart Black');
INSERT INTO author (author_full_name) VALUES ('Hal B Gregersen');
INSERT INTO author (author_full_name) VALUES ('George Kohlrieser');
INSERT INTO author (author_full_name) VALUES ('Elfriede Dustin');
INSERT INTO author (author_full_name) VALUES ('Douglas A. Kimber');
INSERT INTO author (author_full_name) VALUES ('Eric Bauer');
INSERT INTO author (author_full_name) VALUES ('Xuemei Zhang');
INSERT INTO author (author_full_name) VALUES ('Javan Erfanian');
INSERT INTO author (author_full_name) VALUES ('Hung Nguyen');
INSERT INTO author (author_full_name) VALUES ('Peter Wills');
INSERT INTO author (author_full_name) VALUES ('Karl F. Rauscher');
INSERT INTO author (author_full_name) VALUES ('K. Daniel Wong');
INSERT INTO author (author_full_name) VALUES ('Thomas Croda');
INSERT INTO author (author_full_name) VALUES ('Xavier Fernando');
INSERT INTO author (author_full_name) VALUES ('Gustavo Giannattasio');
INSERT INTO author (author_full_name) VALUES ('Niovi Pavlidou');
INSERT INTO author (author_full_name) VALUES ('Dan Fox');
INSERT INTO author (author_full_name) VALUES ('Leliwa Sp. z o. o.');
INSERT INTO author (author_full_name) VALUES ('Kewin Wallace');
INSERT INTO author (author_full_name) VALUES ('David Hucaby');
INSERT INTO author (author_full_name) VALUES ('Wendel Odom');
INSERT INTO author (author_full_name) VALUES ('Mark Grayson');
INSERT INTO author (author_full_name) VALUES ('Scott Wainner');
INSERT INTO author (author_full_name) VALUES ('Kevin Shatzkamer');
INSERT INTO author (author_full_name) VALUES ('Martin J. Feuerstein');
INSERT INTO author (author_full_name) VALUES ('Yasmin Karimli');
INSERT INTO author (author_full_name) VALUES ('Pablo Tapia');
INSERT INTO author (author_full_name) VALUES ('Steve Freeman');
INSERT INTO author (author_full_name) VALUES ('Nat Pryce');
INSERT INTO author (author_full_name) VALUES ('Tomasz Kaczanowski');
INSERT INTO author (author_full_name) VALUES ('Marcin Lis');
INSERT INTO author (author_full_name) VALUES ('Jon Bentley');
INSERT INTO author (author_full_name) VALUES ('Janet Gregory');
INSERT INTO author (author_full_name) VALUES ('Lisa Crispin');
INSERT INTO author (author_full_name) VALUES ('Michal Bartyzel');
INSERT INTO author (author_full_name) VALUES ('Cay S.Horstmann');
INSERT INTO author (author_full_name) VALUES ('Gary Cornell');
INSERT INTO author (author_full_name) VALUES ('Brian Komar');
INSERT INTO author (author_full_name) VALUES ('Ben Smith');
INSERT INTO author (author_full_name) VALUES ('Krzysztof Wesolowski');
INSERT INTO author (author_full_name) VALUES ('Peter C. Patton');
INSERT INTO author (author_full_name) VALUES ('Bijay K. Jayaswal');
INSERT INTO author (author_full_name) VALUES ('Jeffrey J. Fox');
INSERT INTO author (author_full_name) VALUES ('Wesley Chun');
INSERT INTO author (author_full_name) VALUES ('Jeff Forcier');
INSERT INTO author (author_full_name) VALUES ('Paul Bissex');
INSERT INTO author (author_full_name) VALUES ('Tim Parker');
INSERT INTO author (author_full_name) VALUES ('William R. Stanek');
INSERT INTO author (author_full_name) VALUES ('Christopher Scordo');
INSERT INTO author (author_full_name) VALUES ('Tim Bagnall');
INSERT INTO author (author_full_name) VALUES ('Rita Mulcahy');
INSERT INTO author (author_full_name) VALUES ('Robert Wright');
INSERT INTO author (author_full_name) VALUES ('Brian Tracy');
INSERT INTO author (author_full_name) VALUES ('Garry Ridge');
INSERT INTO author (author_full_name) VALUES ('John Stenbeck');
INSERT INTO author (author_full_name) VALUES ('Wojciech Kabacinski');
INSERT INTO author (author_full_name) VALUES ('Grzegorz Danilewicz');
INSERT INTO author (author_full_name) VALUES ('J. D. Parsons');
INSERT INTO author (author_full_name) VALUES ('Harry R. Anderson');
INSERT INTO author (author_full_name) VALUES ('Dave Meier');
INSERT INTO author (author_full_name) VALUES ('Chris Kormanyos');
INSERT INTO author (author_full_name) VALUES ('Lukasz Sosna');
INSERT INTO author (author_full_name) VALUES ('Holger Schwichtenberg');
INSERT INTO author (author_full_name) VALUES ('Bartosz Danowski');
INSERT INTO author (author_full_name) VALUES ('Brian P. Hogan');
INSERT INTO author (author_full_name) VALUES ('Marek Serafin');
INSERT INTO author (author_full_name) VALUES ('James F. Kurose');
INSERT INTO author (author_full_name) VALUES ('Keith W. Ross');
INSERT INTO author (author_full_name) VALUES ('Hazarathaiah Malepati');
INSERT INTO author (author_full_name) VALUES ('training materials');
INSERT INTO author (author_full_name) VALUES ('Chuck Allison');
INSERT INTO author (author_full_name) VALUES ('Williams Anthony');
INSERT INTO author (author_full_name) VALUES ('Fa-Long Luo');
INSERT INTO author (author_full_name) VALUES ('Vinay K. Ingle');
INSERT INTO author (author_full_name) VALUES ('John G. Proakis');
INSERT INTO author (author_full_name) VALUES ('Masound Salehi');
INSERT INTO author (author_full_name) VALUES ('Ruth Colvin Clark');
INSERT INTO author (author_full_name) VALUES ('Clifford Stein');
INSERT INTO author (author_full_name) VALUES ('Cherles E. Leiserson');
INSERT INTO author (author_full_name) VALUES ('Thomas H. Cormen');
INSERT INTO author (author_full_name) VALUES ('Ronald L. Rivest');
INSERT INTO author (author_full_name) VALUES ('Daniel Kline');
INSERT INTO author (author_full_name) VALUES ('Kevin E.Kline');
INSERT INTO author (author_full_name) VALUES ('Brand Hunt');
INSERT INTO author (author_full_name) VALUES ('Andrzej Kierzkowski');
INSERT INTO author (author_full_name) VALUES ('Hudson Paul');
INSERT INTO author (author_full_name) VALUES ('Laura Lemay');
INSERT INTO author (author_full_name) VALUES ('Leon Atkinson');
INSERT INTO author (author_full_name) VALUES ('Zeev Suraski');
INSERT INTO author (author_full_name) VALUES ('Alvin Alexander');
INSERT INTO author (author_full_name) VALUES ('Butcher Paul');
INSERT INTO author (author_full_name) VALUES ('Bruce A Tate Fred Daoud Ian Dees Jack Moffitt');
INSERT INTO author (author_full_name) VALUES ('Warburton Richard');
INSERT INTO author (author_full_name) VALUES ('Max Kanat-Alexander');
INSERT INTO author (author_full_name) VALUES ('Allen B. Downey');
INSERT INTO author (author_full_name) VALUES ('Eric Evans');
INSERT INTO author (author_full_name) VALUES ('Dan Pilone');
INSERT INTO author (author_full_name) VALUES ('Russ Miles');
INSERT INTO author (author_full_name) VALUES ('Kevlin Henney');
INSERT INTO author (author_full_name) VALUES ('Charles Petzold');
INSERT INTO author (author_full_name) VALUES ('Dustin Boswell');
INSERT INTO author (author_full_name) VALUES ('Trevor Foucher');
INSERT INTO author (author_full_name) VALUES ('Greg Wilson');
INSERT INTO author (author_full_name) VALUES ('Andy Oram');
INSERT INTO author (author_full_name) VALUES ('Marshall B. Rosenberg');
INSERT INTO author (author_full_name) VALUES ('Lyssa Adkins');
INSERT INTO author (author_full_name) VALUES ('Ken Martin  and Bill Hoffman');
INSERT INTO author (author_full_name) VALUES ('SungJun Park');
INSERT INTO author (author_full_name) VALUES ('SungHoon Jung');
INSERT INTO author (author_full_name) VALUES ('SungDuck Chun');
INSERT INTO author (author_full_name) VALUES ('SeungJune Yi');
INSERT INTO author (author_full_name) VALUES ('YoungDee Lee');
INSERT INTO author (author_full_name) VALUES ('Art Byrne');
INSERT INTO author (author_full_name) VALUES ('Robert Matusewicz');
INSERT INTO author (author_full_name) VALUES ('Lukasz Grzadko');
INSERT INTO author (author_full_name) VALUES ('Artur Kochowski');
INSERT INTO author (author_full_name) VALUES ('Michal Bartkowiak');
INSERT INTO author (author_full_name) VALUES ('Slawomir Zborowski');
INSERT INTO author (author_full_name) VALUES ('Christopher G.Lasater');
INSERT INTO author (author_full_name) VALUES ('Adam Drozdek');
INSERT INTO author (author_full_name) VALUES ('Matthew Wilson');
INSERT INTO author (author_full_name) VALUES ('Andy Kirby');
INSERT INTO author (author_full_name) VALUES ('Pawel Majdzik');
INSERT INTO author (author_full_name) VALUES ('Jonathan Rasmusson');
INSERT INTO author (author_full_name) VALUES ('Roy Osherove');
INSERT INTO author (author_full_name) VALUES ('Marc Gregorie');
INSERT INTO author (author_full_name) VALUES ('Jeffry G. Andrews');
INSERT INTO author (author_full_name) VALUES ('zhang jun');
INSERT INTO author (author_full_name) VALUES ('Stepanov Alexander');
INSERT INTO author (author_full_name) VALUES ('Daniel E. Rose');
INSERT INTO author (author_full_name) VALUES ('Dake Liu');
INSERT INTO author (author_full_name) VALUES ('white elecia');
INSERT INTO author (author_full_name) VALUES ('ahmadi sassan');
INSERT INTO author (author_full_name) VALUES ('NOKIA');
INSERT INTO author (author_full_name) VALUES ('Scott Blanchard');
INSERT INTO author (author_full_name) VALUES ('TECHCOM Consulting');
INSERT INTO author (author_full_name) VALUES ('Andreas Annen');
INSERT INTO author (author_full_name) VALUES ('SIEMENS');
INSERT INTO author (author_full_name) VALUES ('Nancy Mingus');
INSERT INTO author (author_full_name) VALUES ('praca zbiorowa');
INSERT INTO author (author_full_name) VALUES ('Barry J. Rosenberg');
INSERT INTO author (author_full_name) VALUES ('Sun Technical Publications');
INSERT INTO author (author_full_name) VALUES ('JoAnn T. Hackos');
INSERT INTO author (author_full_name) VALUES ('Alan S. Pringle');
INSERT INTO author (author_full_name) VALUES ('Sarah S. O''Keefe');
INSERT INTO author (author_full_name) VALUES ('William Strunk Jr');
INSERT INTO author (author_full_name) VALUES ('J. Roberto B. De Marca');
INSERT INTO author (author_full_name) VALUES ('Kwang-Cheng Chen');
INSERT INTO author (author_full_name) VALUES ('Microsoft');
INSERT INTO author (author_full_name) VALUES ('Syed Ahson');
INSERT INTO author (author_full_name) VALUES ('Mohammad Ilyas');
INSERT INTO author (author_full_name) VALUES ('Allan Reid');
INSERT INTO author (author_full_name) VALUES ('Mark Ibbotson');
INSERT INTO author (author_full_name) VALUES ('Keith Kelly');
INSERT INTO author (author_full_name) VALUES ('Martin Hewings');
INSERT INTO author (author_full_name) VALUES ('Virginia Evans');
INSERT INTO author (author_full_name) VALUES ('Tim Szigeti');
INSERT INTO author (author_full_name) VALUES ('Christina Hattingh');
INSERT INTO author (author_full_name) VALUES ('Harry G. Perros');
INSERT INTO author (author_full_name) VALUES ('Norman Whitby');
INSERT INTO author (author_full_name) VALUES ('Sam McCarter');
INSERT INTO author (author_full_name) VALUES ('Albert Ellis');
INSERT INTO author (author_full_name) VALUES ('Arthur Lange');
INSERT INTO author (author_full_name) VALUES ('Eknath Easwaran');
INSERT INTO author (author_full_name) VALUES ('Janice Redish');
INSERT INTO author (author_full_name) VALUES ('Timo Halonen');
INSERT INTO author (author_full_name) VALUES ('Juan Melero');
INSERT INTO author (author_full_name) VALUES ('Javier Romero');
INSERT INTO author (author_full_name) VALUES ('Stewart Mader');
INSERT INTO author (author_full_name) VALUES ('Magazine');
INSERT INTO author (author_full_name) VALUES ('Richard L. Hamilton');
INSERT INTO author (author_full_name) VALUES ('Tony Self');
INSERT INTO author (author_full_name) VALUES ('Candace Matthews');
INSERT INTO author (author_full_name) VALUES ('Tanya Peterson');
INSERT INTO author (author_full_name) VALUES ('Diane Martinez');
INSERT INTO author (author_full_name) VALUES ('Carolyn Stevenson');
INSERT INTO author (author_full_name) VALUES ('Carrie Hannigan');
INSERT INTO author (author_full_name) VALUES ('Jorg Henning');
INSERT INTO author (author_full_name) VALUES ('Marita Tjarks-Sobhani');
INSERT INTO author (author_full_name) VALUES ('Michelle Carey');
INSERT INTO author (author_full_name) VALUES ('Jenifer Schlotfeldt');
INSERT INTO author (author_full_name) VALUES ('Laura Bellamy');
INSERT INTO author (author_full_name) VALUES ('Nokia');
INSERT INTO author (author_full_name) VALUES ('Juha Korhonen');
INSERT INTO author (author_full_name) VALUES ('Alex Gillespie');
INSERT INTO author (author_full_name) VALUES ('Thomas Starr');
INSERT INTO author (author_full_name) VALUES ('Massimo Sorbara');
INSERT INTO author (author_full_name) VALUES ('Peter J. Silverman');
INSERT INTO author (author_full_name) VALUES ('John M. Cioffi');
INSERT INTO author (author_full_name) VALUES ('Barbee Davis');
INSERT INTO author (author_full_name) VALUES ('Sploty');
INSERT INTO author (author_full_name) VALUES ('Frederic Laloux');
INSERT INTO author (author_full_name) VALUES ('Freddy Balle');
INSERT INTO author (author_full_name) VALUES ('Michael Balle');
INSERT INTO author (author_full_name) VALUES ('Edgar H. Schein');
INSERT INTO author (author_full_name) VALUES ('Taiichi Ohno');
INSERT INTO author (author_full_name) VALUES ('Allen C. Ward');
INSERT INTO author (author_full_name) VALUES ('Durward K. Sobek II');
INSERT INTO author (author_full_name) VALUES ('W. Edwards Deming');
INSERT INTO author (author_full_name) VALUES ('Roger Schwarz');
INSERT INTO author (author_full_name) VALUES ('Henry Kimsey- House');
INSERT INTO author (author_full_name) VALUES ('Scott Adams');
INSERT INTO author (author_full_name) VALUES ('Andrew Mayo');
INSERT INTO author (author_full_name) VALUES ('Jacek Wozniak');
INSERT INTO author (author_full_name) VALUES ('David Farley');
INSERT INTO author (author_full_name) VALUES ('James Bach');
INSERT INTO author (author_full_name) VALUES ('Cem Kaner');
INSERT INTO author (author_full_name) VALUES ('Bret Pettichord');
INSERT INTO author (author_full_name) VALUES ('Sam Newman');
INSERT INTO author (author_full_name) VALUES ('Jennifer Greene');
INSERT INTO author (author_full_name) VALUES ('Andrew Stellman');
INSERT INTO author (author_full_name) VALUES ('Milosz Brzezinski');
INSERT INTO author (author_full_name) VALUES ('Mariusz Chrapko');
INSERT INTO author (author_full_name) VALUES ('Mariusz Kapusta');
INSERT INTO author (author_full_name) VALUES ('Aaron J. Shenhar');
INSERT INTO author (author_full_name) VALUES ('Dov Dvir');
INSERT INTO author (author_full_name) VALUES ('Project Management Institute');
INSERT INTO author (author_full_name) VALUES ('Dom Wydawniczy Anna Adamczyk');
INSERT INTO author (author_full_name) VALUES ('Autor autor');
INSERT INTO author (author_full_name) VALUES ('John Snow');
INSERT INTO author (author_full_name) VALUES ('Diana Lea');
INSERT INTO author (author_full_name) VALUES ('Collin McIntosh');
INSERT INTO author (author_full_name) VALUES ('The University of Chicago Press');
INSERT INTO author (author_full_name) VALUES ('Rick McDonald');
INSERT INTO author (author_full_name) VALUES ('Vaughan Jones');
INSERT INTO author (author_full_name) VALUES ('Sue Kay');
INSERT INTO author (author_full_name) VALUES ('Adrian Farrel');
INSERT INTO author (author_full_name) VALUES ('Philip Kerr');
INSERT INTO author (author_full_name) VALUES ('Ceri Jones');
INSERT INTO author (author_full_name) VALUES ('Wayne Lewis');
INSERT INTO author (author_full_name) VALUES ('Alexander Giulietti');
INSERT INTO author (author_full_name) VALUES ('Liesbet Van der Perre');
INSERT INTO author (author_full_name) VALUES ('Bruno Bougard');
INSERT INTO author (author_full_name) VALUES ('Maxime Pelcat');
INSERT INTO author (author_full_name) VALUES ('Davide Di Gennaro');
INSERT INTO author (author_full_name) VALUES ('Cisco Learning Product');
INSERT INTO author (author_full_name) VALUES ('Stefan Zeidenitz');
INSERT INTO author (author_full_name) VALUES ('Sahoko Kaji');
INSERT INTO author (author_full_name) VALUES ('Nick Yapp');
INSERT INTO author (author_full_name) VALUES ('Ewa Lipniacka');
INSERT INTO author (author_full_name) VALUES ('Zhu Song');
INSERT INTO author (author_full_name) VALUES ('William Ury');
INSERT INTO author (author_full_name) VALUES ('Roger Fisher');
INSERT INTO author (author_full_name) VALUES ('Douglas Stone');
INSERT INTO author (author_full_name) VALUES ('Gojko Adzic');
INSERT INTO author (author_full_name) VALUES ('Luke Hohmann');
INSERT INTO author (author_full_name) VALUES ('Ronald R. Lehmann');
INSERT INTO author (author_full_name) VALUES ('Ellen Gottesdiener');
INSERT INTO author (author_full_name) VALUES ('Tarja Moles');
INSERT INTO author (author_full_name) VALUES ('Harold Abelson and Gerald Jay Sussman');
INSERT INTO author (author_full_name) VALUES ('Robert Harper');
INSERT INTO author (author_full_name) VALUES ('Andrew W. Appel');
INSERT INTO author (author_full_name) VALUES ('Steven S. Muchnick');
INSERT INTO author (author_full_name) VALUES ('Geoff Watts');
INSERT INTO author (author_full_name) VALUES ('Roman Pichler');
INSERT INTO author (author_full_name) VALUES ('Mark Schwartz');
INSERT INTO author (author_full_name) VALUES ('Peter Senge');
INSERT INTO author (author_full_name) VALUES ('Luciano Ramalho');
INSERT INTO author (author_full_name) VALUES ('Gabriele Lanaro');
INSERT INTO author (author_full_name) VALUES ('Miguel Grinberg');
INSERT INTO author (author_full_name) VALUES ('Robert Shimonski');
INSERT INTO author (author_full_name) VALUES ('Jason van Gumster');
INSERT INTO author (author_full_name) VALUES ('Adriaan de Jonge');
INSERT INTO author (author_full_name) VALUES ('Adam Freeman');
INSERT INTO author (author_full_name) VALUES ('Lea Verou');
INSERT INTO author (author_full_name) VALUES ('Sean P. Kane');
INSERT INTO author (author_full_name) VALUES ('Karl Matthias');
INSERT INTO author (author_full_name) VALUES ('Haralambos Marmanis');
INSERT INTO author (author_full_name) VALUES ('Dmitry Babenko');
INSERT INTO author (author_full_name) VALUES ('Douglas McIlwraith');
INSERT INTO author (author_full_name) VALUES ('Stoyan Stefanov');
INSERT INTO author (author_full_name) VALUES ('Christian Bauer');
INSERT INTO author (author_full_name) VALUES ('Gary Gregory');
INSERT INTO author (author_full_name) VALUES ('Gavin King');
INSERT INTO author (author_full_name) VALUES ('David Herman');
INSERT INTO author (author_full_name) VALUES ('Jon Duckett');
INSERT INTO author (author_full_name) VALUES ('Douglas Crockford');
INSERT INTO author (author_full_name) VALUES ('Simon Timms');
INSERT INTO author (author_full_name) VALUES ('Kyle Simpson');
INSERT INTO author (author_full_name) VALUES ('Mateusz Grzesiak');
INSERT INTO author (author_full_name) VALUES ('Jaroslaw Szostka');
INSERT INTO author (author_full_name) VALUES ('Michael Kerrisk');
INSERT INTO author (author_full_name) VALUES ('Randal W. Beard');
INSERT INTO author (author_full_name) VALUES ('Sam Ruby');
INSERT INTO author (author_full_name) VALUES ('Neuland');
INSERT INTO author (author_full_name) VALUES ('Karolina Zmitrowicz');
INSERT INTO author (author_full_name) VALUES ('Adam Roman');
INSERT INTO author (author_full_name) VALUES ('Naim Dahnoun');
INSERT INTO author (author_full_name) VALUES ('GlobalStandard');
INSERT INTO author (author_full_name) VALUES ('Czachorski Tadeusz');
INSERT INTO author (author_full_name) VALUES ('Thomas Erikson');
INSERT INTO author (author_full_name) VALUES ('Beata Rzepka');
INSERT INTO author (author_full_name) VALUES ('Curt Coffman');
INSERT INTO author (author_full_name) VALUES ('Marcus Buckingham');
INSERT INTO author (author_full_name) VALUES ('S.Wrycza');
INSERT INTO author (author_full_name) VALUES ('Olof Liberg');
INSERT INTO author (author_full_name) VALUES ('E. Douglas Jensen');
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Applied C++ : Practical Techniques for Building Better Software', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('imbutzfjpv', 1, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,1);
INSERT INTO book_details_authors VALUES (1, 1);
INSERT INTO book_details_authors VALUES (1, 2);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Communities of Practice', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('jpmzmeeoor', 2, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,2);
INSERT INTO book_details_authors VALUES (2, 3);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'The Five Dysfunctions of a Team', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('xkycdjdnxv', 3, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,3);
INSERT INTO book_details_authors VALUES (3, 4);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'The Future of Management', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('smttjucpab', 4, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,4);
INSERT INTO book_details_authors VALUES (4, 5);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Modern C++ Design', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('zoejivpzku', 5, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,5);
INSERT INTO book_details_authors VALUES (5, 6);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Essential Linux Device Drivers', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('eqihdanait', 6, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,6);
INSERT INTO book_details_authors VALUES (6, 7);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Embedded Linux Primer', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('vcstdbdcph', 7, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,7);
INSERT INTO book_details_authors VALUES (7, 8);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'More Exceptional C++', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('vveblwnoau', 8, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,8);
INSERT INTO book_details_authors VALUES (8, 9);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'C++ Network Programming, vol. 1', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('qgccaaxaww', 9, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,9);
INSERT INTO book_details_authors VALUES (9, 10);
INSERT INTO book_details_authors VALUES (9, 11);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'C++ Network Programming, vol. 2', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('bnakvcqhjs', 10, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,10);
INSERT INTO book_details_authors VALUES (10, 11);
INSERT INTO book_details_authors VALUES (10, 10);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Accelerated C++. Practical Programming by Example', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('frdycyyapc', 11, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,11);
INSERT INTO book_details_authors VALUES (11, 12);
INSERT INTO book_details_authors VALUES (11, 13);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Hard Facts', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('skjcnhjaak', 12, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,12);
INSERT INTO book_details_authors VALUES (12, 14);
INSERT INTO book_details_authors VALUES (12, 15);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Vademecum Teleinformatyka III', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('eidbuohjqv', 13, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,13);
INSERT INTO book_details_authors VALUES (13, 16);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Clean Code. A Handbook of Agile Software Craftsmanship', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('gylcfafsxh', 14, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,14);
INSERT INTO book_details_authors VALUES (14, 17);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Continuous Integration - Improving Software Quality', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('nlhbdicqtm', 15, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,15);
INSERT INTO book_details_authors VALUES (15, 18);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Working effectively with legacy code', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('hypzuhgebb', 16, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,16);
INSERT INTO book_details_authors VALUES (16, 19);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Agile Software Development with Scrum', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('ftoodhxhcr', 17, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,17);
INSERT INTO book_details_authors VALUES (17, 20);
INSERT INTO book_details_authors VALUES (17, 21);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'xUnit Test Patterns - Refactoring, Test Code', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('puwxgzljru', 18, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,18);
INSERT INTO book_details_authors VALUES (18, 22);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Agile Retrospectives. Making Good Teams Great', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('cqmudtqnqx', 19, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,19);
INSERT INTO book_details_authors VALUES (19, 23);
INSERT INTO book_details_authors VALUES (19, 24);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Test-Driven Development: By Example', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('hteaumemnp', 20, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,20);
INSERT INTO book_details_authors VALUES (20, 25);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Designing Interfaces: Patterns for Effective Interaction Design', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('rxjxiuivbr', 21, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,21);
INSERT INTO book_details_authors VALUES (21, 26);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Oprogramowanie komponentowe, obiekty to za mało', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('hrwvbqnpku', 22, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,22);
INSERT INTO book_details_authors VALUES (22, 27);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Refactoring: Improving the Design of Existing Code', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('hsfktlnbba', 23, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,23);
INSERT INTO book_details_authors VALUES (23, 25);
INSERT INTO book_details_authors VALUES (23, 28);
INSERT INTO book_details_authors VALUES (23, 29);
INSERT INTO book_details_authors VALUES (23, 30);
INSERT INTO book_details_authors VALUES (23, 31);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Java Concurrency in Practice', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('iyheiyywjj', 24, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,24);
INSERT INTO book_details_authors VALUES (24, 32);
INSERT INTO book_details_authors VALUES (24, 33);
INSERT INTO book_details_authors VALUES (24, 34);
INSERT INTO book_details_authors VALUES (24, 35);
INSERT INTO book_details_authors VALUES (24, 36);
INSERT INTO book_details_authors VALUES (24, 37);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Thinking in C++, tom 2', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('wgxcubeggk', 25, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,25);
INSERT INTO book_details_authors VALUES (25, 38);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Symfonia C++', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('ddgushmyls', 26, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,26);
INSERT INTO book_details_authors VALUES (26, 39);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Szkoła programowania, Język C++', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('wwovkehlsv', 27, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,27);
INSERT INTO book_details_authors VALUES (27, 40);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Practical Qt', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('uclwbzxwgm', 28, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,28);
INSERT INTO book_details_authors VALUES (28, 41);
INSERT INTO book_details_authors VALUES (28, 42);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Programming with Qt, 2nd edition, Covers Qt3', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('prxjtrggvm', 29, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,29);
INSERT INTO book_details_authors VALUES (29, 42);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Język C++ Standardy kodowania', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('xwdbyqvzav', 30, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,30);
INSERT INTO book_details_authors VALUES (30, 6);
INSERT INTO book_details_authors VALUES (30, 9);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Essential C++', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('liugnkhglb', 31, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,31);
INSERT INTO book_details_authors VALUES (31, 43);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Large-scale Software Architecture (A parctical guide using UML)', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('keybuyhlcy', 32, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,32);
INSERT INTO book_details_authors VALUES (32, 44);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'SOLARIS 8, Sparc Platform Edition for Sun Computers Systems', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('qtkxgmtvrv', 33, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,33);
INSERT INTO book_details_authors VALUES (33, 45);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'CDMA Principles of Spread Spectrum Communication', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('yplpyiuyww', 34, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,34);
INSERT INTO book_details_authors VALUES (34, 46);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, '3G Evolution: HSPA and LTE for Mobile Broadband', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('bplnfysnrd', 35, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,35);
INSERT INTO book_details_authors VALUES (35, 47);
INSERT INTO book_details_authors VALUES (35, 48);
INSERT INTO book_details_authors VALUES (35, 49);
INSERT INTO book_details_authors VALUES (35, 50);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Tektronix K1297-G20, June, 2000', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('ygkiqamdfz', 36, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,36);
INSERT INTO book_details_authors VALUES (36, 51);
INSERT INTO book_details_authors VALUES (36, 52);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Evolved Packet System (EPS); The LTE an SAE evolution of 3G UMTS', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('ynmdleetfl', 37, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,37);
INSERT INTO book_details_authors VALUES (37, 53);
INSERT INTO book_details_authors VALUES (37, 54);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Motywacja pod lupą', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('ccjoytuxwe', 38, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,38);
INSERT INTO book_details_authors VALUES (38, 55);
INSERT INTO book_details_authors VALUES (38, 56);
INSERT INTO book_details_authors VALUES (38, 57);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'The Pragmatic Programmer', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('uwtlzecptf', 39, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,39);
INSERT INTO book_details_authors VALUES (39, 58);
INSERT INTO book_details_authors VALUES (39, 59);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'ATM Networks, concepts, protocols, applications', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('okxijdamvq', 40, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,40);
INSERT INTO book_details_authors VALUES (40, 60);
INSERT INTO book_details_authors VALUES (40, 61);
INSERT INTO book_details_authors VALUES (40, 62);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Extreme Programming Explained. Embrace Change', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('gnlvtqzxwt', 41, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,41);
INSERT INTO book_details_authors VALUES (41, 63);
INSERT INTO book_details_authors VALUES (41, 25);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'Overcoming the Five dysunctions of a team a field guide', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('zkygkuaixn', 42, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,42);
INSERT INTO book_details_authors VALUES (42, 4);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'The Art of Assembly Language', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('rlqagojoxh', 43, 1, 8);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (8 ,43);
INSERT INTO book_details_authors VALUES (43, 64);
INSERT INTO book_details (isbn, title, description, publication_date, is_removable) VALUES (0000000000000, 'The Art of Computer Programming vol.1 (Fundamental Algorithms 3rd ed.)', '', '2018-09-01', 'true');
INSERT INTO book (signature, book_details_id, book_status_id, current_owner_id) VALUES ('benlenegdm', 44, 1, 7);
INSERT INTO book_owner_id (owner_id, book_id) VALUES (7 ,44);
INSERT INTO book_details_authors VALUES (44, 65);
